# Generated by Django 3.2.2 on 2021-05-31 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=30, verbose_name='Отчество')),
                ('position', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('Jn', 'Junior'), ('Md', 'Middle'), ('Sr', 'Senior'), ('Dr', 'Director'), ('Ce', 'CEO')], default='Jn', max_length=100)),
                ('employment_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата приёма на работу')),
                ('email', models.EmailField(default='email@example.com', max_length=200, unique=True, verbose_name='Email')),
                ('salary', models.DecimalField(decimal_places=2, default=0, help_text='указывать сумму в долларах', max_digits=8, verbose_name='Зарплата')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, help_text='указывать сумму в долларах', max_digits=16, verbose_name='Всего выплачено')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
