# Generated by Django 3.2.3 on 2021-05-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='email@example.com', max_length=200, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.CharField(choices=[('Jn', 'Junior'), ('Md', 'Middle'), ('Sr', 'Senior'), ('Dr', 'Director'), ('Ce', 'CEO')], default='Jn', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(max_length=30, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
